### ISSUE TITLE
plugin qgis 

### ISSUE THREAD

**Issue by jbdesbas** [bchartier/french-locality-name-shortener#4]
💡Implémenter le programme sous forme de plugin Qgis : ajout d'une une nouvelle fonction dans le moteur d'expression pour faire des étiquettes raccourcies à la volée.
(Ou ajouter cette fonctionnalité à un plugin existant ?)

**Comment by bchartier** [comment]
Effectivement, cela pourrait être intéressant.

**Comment by jbdesbas** [comment]
En cours ici : https://github.com/jbdesbas/qgis-flns
